# Generated by Django 3.2.4 on 2021-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calipers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.IntegerField(verbose_name='Инвентарный номер')),
                ('fac_number', models.IntegerField(verbose_name='Заводской номер')),
                ('accuracy', models.CharField(default='', max_length=50, verbose_name='Точность')),
                ('meas_limit', models.CharField(default='', max_length=100, verbose_name='Предел измерения')),
                ('last_date_check', models.DateTimeField(verbose_name='Дата последней проверки')),
                ('next_date_check', models.DateTimeField(verbose_name='Дата следующей проверки')),
                ('checked', models.CharField(default='', max_length=100, verbose_name='Фамилия И.О. проверяющего')),
            ],
            options={
                'verbose_name': 'Штангенциркуль',
                'verbose_name_plural': 'Штангенциркули',
            },
        ),
        migrations.CreateModel(
            name='Micrometers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.IntegerField(verbose_name='Инвентарный номер')),
                ('fac_number', models.IntegerField(verbose_name='Заводской номер')),
                ('accuracy', models.CharField(default='', max_length=50, verbose_name='Точность')),
                ('meas_limit', models.CharField(default='', max_length=100, verbose_name='Предел измерения')),
                ('last_date_check', models.DateTimeField(verbose_name='Дата последней проверки')),
                ('next_date_check', models.DateTimeField(verbose_name='Дата следующей проверки')),
                ('checked', models.CharField(default='', max_length=100, verbose_name='Фамилия И.О. проверяющего')),
            ],
            options={
                'verbose_name': 'Микрометр',
                'verbose_name_plural': 'Микрометры',
            },
        ),
        migrations.AlterModelOptions(
            name='instruments',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
    ]
